name: ci

on:
  pull_request:
    branches: [ main ]
  push:
    tags: [ 'v*' ]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
              
      - name: check
        if: github.event_name == 'pull_request'
        run: make check

      - if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
        run: brew install upx

      - uses: docker/login-action@v1
        if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
        run: make ci/release
      
      - uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
        with:
          path: dist/*
